### ISSUE TITLE
Sensodrive Expansion

### ISSUE THREAD

**Issue by FallenWyvern** [tud-hri/joan#33]
I'm using Carla + JOAN purely as a Driver-In-The-Loop solution, but I didn't realize that support for anything *other* than the wheel isn't there. I'll start tinkering with the python code to see if I can generate the signals for pedals, but it'd be nice if that was already part of the package.

**Comment by OlgerSiebinga** [comment]
Hi @FallenWyvern,

I don't completely understand what you mean here. JOAN supports Sensodrive steering wheels and the corresponding gas and brake pedals. If you connect a sensodrive setup to an ego vehicle in the GUI you should be able to drive it like an automatic gearbox vehicle. Furthermore, you can access the raw signals (steering angle, gas-, and brake pedal inputs) through the shared variables interface. All raw signals are also available in the datarecorder for saving and post processing.

Besides the sensodrive hardware, JOAN supports USB steering wheels (e.g., logitech steering wheel and pedasl). You have to manually set the channels for the steering angle, gas, and brake inputs in the hardware manager GUI. But once that's done you can control an ego vehicle and have access to the raw signals through the shared variables.

In both cases, there is no need to make any adjustments to the code to use pedal inputs. It should be all possible from the GUI.

Hope this helps! Let me know if you have any further questions.
