### ISSUE TITLE
I prepared everything, but when I try to run main.py. Joan still failed to connect to carla.

### ISSUE THREAD

**Issue by timeriverclef** [tud-hri/joan#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by OlgerSiebinga** [comment]
Hi @timeriverclef, 
Can you give me some more information about what's happening? I'd appreciate it if you could fill in the issue template. But at a minimum, I'd like to know if you're getting an error message, which version of JOAN you are using, and if you ran into any trouble during the installation process.

**Comment by timeriverclef** [comment]
OK，I am using the Joan 1.1.0. I think I find the reason. It was found that the computer memory was too low, which caused it to run too slowly, and the error was reported when it timed out, and it was necessary to change the time to search for and modify self.client.set_timeout and client.set_timeout in the project.

**Comment by OlgerSiebinga** [comment]
Alright, good to know that you found and fixed the problem!
